# Introduction

Life expectancy is a statistical projection of the number of years a person can expect to live and is an important measure of a population’s general health and well being. It is a mortality measure that can provide significant insights into a country’s social and economics conditions, as well as the effectiveness of it’s healthcare systems. Research into life expectancy can potentially highlight areas that may need intervention to address any disparities and inequalities that may exists. Additionally, it can guide efforts to improve health outcomes by addressing areas where change may be needed in public health. 

In the last century, life expectancy has steadily increased in most countries, and is a result of ongoing process in improvements in health[1]. The advancement in technology, medical health, and higher standard of living have contributed to this positive trend. According to Riley(2001), increasing longevity can be achieved by improving six key areas: public health, medicine, wealth and income, nutrition, behavior, and education[2]. In a 2020 study by The Journals of Gerontology, wealth was noted as the most crucial factor in longevity and health[3]. Wealth allow access to better healthcare and healthier lifestyles,which can lead to longer, healthier lives.

# Research Context and Purpose

While the link between wealth and life expectancy has been established, the interplay between economic and and environmental factors across countries worldwide is what this study aims to explore. By analyzing the relationship, this research hope the members of the general population who are interested in topics involving health and longevity can identify key factors influencing life expectancy and make informed decisions to adopt healthier lifestyles. 

In this project, the research question I aim to examine is:
How do economic and environmental factors affect life expectancy across different countries?

